name: Go
on: [push]
jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -coverprofile=coverage.out ./

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
        fail_ci_if_error: true
